import { NextResponse } from "next/server";
import { getServerUser } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import type { LocationSelection } from "@/lib/location-types";
import { saveSellerPrimaryLocation } from "@/lib/turkiye-locations";
function text(value: unknown, max: number) { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function safeUrl(value: unknown) { const result = text(value, 1000); if (!result) return null; try { const url = new URL(result); return url.protocol === "https:" ? result : null; } catch { return null; } }
export async function PATCH(request: Request) { const user = await getServerUser(); if (!user) return NextResponse.json({ error: "Önce giriş yapın." }, { status: 401 }); if (user.role !== "NUT_STORE") return NextResponse.json({ error: "Bu işlem yalnız kuruyemişçi hesabına açıktır." }, { status: 403 }); const body = (await request.json().catch(() => null)) as Record<string, unknown> | null; const name = text(body?.name, 120); if (!name) return NextResponse.json({ error: "İşletme adı zorunludur." }, { status: 400 }); const supabase = await createSupabaseServerClient(); const { error } = await supabase.from("stores").update({ name, description: text(body?.description, 1500) || null, phone: text(body?.phone, 20) || null, address: text(body?.address, 500) || null, logo_url: safeUrl(body?.logoUrl), cover_url: safeUrl(body?.coverUrl) }).eq("owner_id", user.id); if (error) return NextResponse.json({ error: "Mağaza profili güncellenemedi." }, { status: 400 }); if (body?.location && typeof body.location === "object") { try { await saveSellerPrimaryLocation(createSupabaseAdminClient(), user.id, body.location as LocationSelection); } catch (locationError) { return NextResponse.json({ error: locationError instanceof Error ? locationError.message : "Mahalle kaydedilemedi." }, { status: 400 }); } } return NextResponse.json({ ok: true }); }
